// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXhLWSzC-Nx3dMXs53lFFiqUXdeA1nFs0',
    appId: '1:275404572479:web:51339c914562551254f58a',
    messagingSenderId: '275404572479',
    projectId: 'waste-app-f799b',
    authDomain: 'waste-app-f799b.firebaseapp.com',
    storageBucket: 'waste-app-f799b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhxtrxg1g1I3uBrfK7bBQBS9UDaotexI0',
    appId: '1:275404572479:android:6b947ba8462eb8d054f58a',
    messagingSenderId: '275404572479',
    projectId: 'waste-app-f799b',
    storageBucket: 'waste-app-f799b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHFGWgM3HXXf6sej2aDK8iDJ_PSfrONQU',
    appId: '1:275404572479:ios:046552abb9836dd454f58a',
    messagingSenderId: '275404572479',
    projectId: 'waste-app-f799b',
    storageBucket: 'waste-app-f799b.appspot.com',
    iosClientId: '275404572479-d0ulaqevt24neme5c29r6so2qnbloh7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasteTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHFGWgM3HXXf6sej2aDK8iDJ_PSfrONQU',
    appId: '1:275404572479:ios:046552abb9836dd454f58a',
    messagingSenderId: '275404572479',
    projectId: 'waste-app-f799b',
    storageBucket: 'waste-app-f799b.appspot.com',
    iosClientId: '275404572479-d0ulaqevt24neme5c29r6so2qnbloh7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasteTime',
  );
}
